[package]
name = "dexo-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ropey.workspace = true
sqlparser.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tree-sitter.workspace = true
tree-sitter-sequel.workspace = true

[dev-dependencies]
proptest.workspace = true
