use dexo_driver_api::TransactionState;

use super::{FlowIntent, PaletteEntry, PaletteInvocation};
use crate::action::{Action, FocusTarget};
use crate::model::Model;

pub fn palette_entries(model: &Model) -> Vec<PaletteEntry> {
    vec![
        PaletteEntry {
            id: "workbench.quit",
            title: "Quit",
            keywords: &["exit", "close"],
            shortcut: Some("Ctrl+Q"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::Quit),
        },
        PaletteEntry {
            id: "palette.open",
            title: "Command Palette",
            keywords: &["commands", "search"],
            shortcut: Some("Ctrl+P"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenPalette),
        },
        PaletteEntry {
            id: "query.execute",
            title: "Execute Query",
            keywords: &["run", "sql"],
            shortcut: Some("F5"),
            disabled_reason: if model.active_document().text().trim().is_empty() {
                Some("editor is empty".into())
            } else {
                None
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ExecuteQuery),
        },
        PaletteEntry {
            id: "query.execute_statement",
            title: "Execute Statement",
            keywords: &["run", "sql", "cursor"],
            shortcut: Some("Ctrl+Enter"),
            disabled_reason: if model.active_document().text().trim().is_empty() {
                Some("editor is empty".into())
            } else {
                None
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ExecuteStatement),
        },
        PaletteEntry {
            id: "query.execute_selection",
            title: "Execute Selection",
            keywords: &["run", "sql", "selected"],
            shortcut: None,
            disabled_reason: if model.active_document().selection().is_none() {
                Some("no selection".into())
            } else {
                None
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ExecuteSelection),
        },
        PaletteEntry {
            id: "query.execute_document",
            title: "Execute Document",
            keywords: &["run", "sql", "all"],
            shortcut: Some("F5"),
            disabled_reason: if model.active_document().text().trim().is_empty() {
                Some("editor is empty".into())
            } else {
                None
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ExecuteDocument),
        },
        PaletteEntry {
            id: "query.cancel",
            title: "Cancel Query",
            keywords: &["stop", "abort"],
            shortcut: Some("Ctrl+C"),
            disabled_reason: if model.active_query.is_none() {
                Some("no running query".into())
            } else {
                None
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CancelQuery),
        },
        PaletteEntry {
            id: "transaction.begin",
            title: "Begin Transaction",
            keywords: &["tx", "begin", "start"],
            shortcut: None,
            disabled_reason: if model.active_session.is_some()
                && model.transaction == TransactionState::Idle
            {
                None
            } else {
                Some("session is not idle".into())
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::BeginTransaction),
        },
        PaletteEntry {
            id: "transaction.savepoint",
            title: "Create Savepoint",
            keywords: &["tx", "savepoint"],
            shortcut: None,
            disabled_reason: if model.transaction == TransactionState::Active {
                None
            } else {
                Some("no active transaction".into())
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::Savepoint),
        },
        PaletteEntry {
            id: "transaction.rollback_savepoint",
            title: "Rollback Savepoint",
            keywords: &["tx", "savepoint", "rollback"],
            shortcut: None,
            disabled_reason: if model.transaction == TransactionState::Active {
                None
            } else {
                Some("no active transaction".into())
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::RollbackSavepoint),
        },
        PaletteEntry {
            id: "transaction.release_savepoint",
            title: "Release Savepoint",
            keywords: &["tx", "savepoint", "release"],
            shortcut: None,
            disabled_reason: if model.transaction == TransactionState::Active {
                None
            } else {
                Some("no active transaction".into())
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ReleaseSavepoint),
        },
        PaletteEntry {
            id: "transaction.commit",
            title: "Commit Transaction",
            keywords: &["tx", "commit"],
            shortcut: None,
            disabled_reason: if model.transaction == TransactionState::Active {
                None
            } else {
                Some("no active transaction".into())
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CommitTransaction),
        },
        PaletteEntry {
            id: "transaction.rollback",
            title: "Rollback Transaction",
            keywords: &["tx", "abort"],
            shortcut: None,
            disabled_reason: if matches!(
                model.transaction,
                TransactionState::Active | TransactionState::Failed
            ) {
                None
            } else {
                Some("no active transaction".into())
            },
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::RollbackTransaction),
        },
        PaletteEntry {
            id: "help.open",
            title: "Show Keybindings",
            keywords: &["help", "keys", "cheatsheet", "shortcuts"],
            shortcut: Some("F1"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ToggleHelp),
        },
        PaletteEntry {
            id: "focus.explorer",
            title: "Focus Explorer",
            keywords: &["sidebar", "tree"],
            shortcut: Some("Alt+1"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::Focus(FocusTarget::Explorer)),
        },
        PaletteEntry {
            id: "focus.editor",
            title: "Focus Editor",
            keywords: &["sql", "query"],
            shortcut: Some("Alt+2"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::Focus(FocusTarget::Editor)),
        },
        PaletteEntry {
            id: "focus.results",
            title: "Focus Results",
            keywords: &["grid", "rows"],
            shortcut: Some("Alt+3"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::Focus(FocusTarget::Results)),
        },
        PaletteEntry {
            id: "focus.inspector",
            title: "Focus Inspector",
            keywords: &["details", "side"],
            shortcut: Some("Alt+4"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::Focus(FocusTarget::Inspector)),
        },
        PaletteEntry {
            id: "layout.cycle",
            title: "Cycle Layout",
            keywords: &["preset", "panes", "split"],
            shortcut: Some("F10"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CycleLayout),
        },
        PaletteEntry {
            id: "layout.results_focus",
            title: "Layout: Results focus",
            keywords: &["preset", "wide", "grid"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::LayoutResultsFocus),
        },
        PaletteEntry {
            id: "layout.hide_inspector",
            title: "Hide Inspector",
            keywords: &["layout", "pane", "toggle"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::HideInspector),
        },
        PaletteEntry {
            id: "layout.reset",
            title: "Reset layout",
            keywords: &["preset", "default", "panes"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResetLayout),
        },
        PaletteEntry {
            id: "layout.results_grow",
            title: "Grow Results Pane",
            keywords: &["split", "height"],
            shortcut: Some("Alt+="),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::GrowResults),
        },
        PaletteEntry {
            id: "layout.results_shrink",
            title: "Shrink Results Pane",
            keywords: &["split", "height"],
            shortcut: Some("Alt+-"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ShrinkResults),
        },
        PaletteEntry {
            id: "layout.explorer_grow",
            title: "Grow Explorer Pane",
            keywords: &["split", "width"],
            shortcut: Some("Alt+]"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::GrowExplorer),
        },
        PaletteEntry {
            id: "layout.explorer_shrink",
            title: "Shrink Explorer Pane",
            keywords: &["split", "width"],
            shortcut: Some("Alt+["),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ShrinkExplorer),
        },
        PaletteEntry {
            id: "layout.inspector_grow",
            title: "Grow Inspector Pane",
            keywords: &["split", "width"],
            shortcut: Some("Alt+="),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::GrowInspector),
        },
        PaletteEntry {
            id: "layout.inspector_shrink",
            title: "Shrink Inspector Pane",
            keywords: &["split", "width"],
            shortcut: Some("Alt+-"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ShrinkInspector),
        },
        PaletteEntry {
            id: "data.copy.csv",
            title: "Copy as CSV",
            keywords: &["clipboard", "grid"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CopyGrid(
                dexo_app::data::CopyFormat::Csv,
            )),
        },
        PaletteEntry {
            id: "data.copy.text",
            title: "Copy as Text",
            keywords: &["clipboard", "grid"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CopyGrid(
                dexo_app::data::CopyFormat::Text,
            )),
        },
        PaletteEntry {
            id: "data.copy.json",
            title: "Copy as JSON",
            keywords: &["clipboard", "grid"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CopyGrid(
                dexo_app::data::CopyFormat::Json,
            )),
        },
        PaletteEntry {
            id: "data.copy.markdown",
            title: "Copy as Markdown",
            keywords: &["clipboard", "grid"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CopyGrid(
                dexo_app::data::CopyFormat::Markdown,
            )),
        },
        PaletteEntry {
            id: "data.copy.sql",
            title: "Copy as SQL",
            keywords: &["clipboard", "grid"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CopyGrid(
                dexo_app::data::CopyFormat::Sql,
            )),
        },
        PaletteEntry {
            id: "data.apply",
            title: "Apply Changes",
            keywords: &["mutate", "save"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ApplyChanges),
        },
        PaletteEntry {
            id: "data.revert",
            title: "Revert Changes",
            keywords: &["undo", "discard"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::RevertChanges),
        },
        PaletteEntry {
            id: "data.nav_back",
            title: "Data Navigate Back",
            keywords: &["crumb", "related"],
            shortcut: Some("b"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::DataNavBack),
        },
        PaletteEntry {
            id: "data.page_next",
            title: "Next Data Page",
            keywords: &["page", "offset"],
            shortcut: Some("n"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::NextDataPage),
        },
        PaletteEntry {
            id: "data.page_prev",
            title: "Previous Data Page",
            keywords: &["page", "offset"],
            shortcut: Some("p"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::PrevDataPage),
        },
        PaletteEntry {
            id: "data.sort",
            title: "Apply Remote Sort",
            keywords: &["order", "query"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ApplyRemoteSort),
        },
        PaletteEntry {
            id: "data.filter",
            title: "Apply Remote Filter",
            keywords: &["where", "query"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ApplyRemoteFilter),
        },
        PaletteEntry {
            id: "data.review",
            title: "Review Changes",
            keywords: &["apply", "edit"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenReview),
        },
        PaletteEntry {
            id: "data.related",
            title: "Open Related",
            keywords: &["foreign", "key"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenRelated),
        },
        PaletteEntry {
            id: "data.inspect",
            title: "Inspect Value",
            keywords: &["viewer", "json"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::InspectValue),
        },
        PaletteEntry {
            id: "schema.preview",
            title: "Preview DDL",
            keywords: &["schema", "ddl", "form"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenDdlPreview),
        },
        PaletteEntry {
            id: "schema.raw",
            title: "Apply Raw DDL",
            keywords: &["sql", "escape"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ApplyRawDdl),
        },
        PaletteEntry {
            id: "schema.diff",
            title: "Compare Schema",
            keywords: &["diff", "migration", "snapshot"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenSchemaDiff),
        },
        PaletteEntry {
            id: "transfer.export",
            title: "Export Data",
            keywords: &["csv", "json", "file"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenTransfer),
        },
        PaletteEntry {
            id: "transfer.import",
            title: "Import Data",
            keywords: &["csv", "json", "file"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenTransfer),
        },
        PaletteEntry {
            id: "backup.dump",
            title: "Native Backup",
            keywords: &["pg_dump", "mysqldump"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenBackup),
        },
        PaletteEntry {
            id: "backup.restore",
            title: "Native Restore",
            keywords: &["pg_restore", "mysql"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenRestore),
        },
        PaletteEntry {
            id: "schema.security",
            title: "Manage Grants",
            keywords: &["role", "user", "grant"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenSecurity),
        },
        PaletteEntry {
            id: "explain.open",
            title: "Explain Plan",
            keywords: &["analyze", "plan", "cost"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenExplain),
        },
        PaletteEntry {
            id: "admin.sessions",
            title: "Inspect Sessions",
            keywords: &["locks", "cancel", "terminate"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenAdmin),
        },
        PaletteEntry {
            id: "mcp.profiles",
            title: "MCP Profiles",
            keywords: &["mcp", "allowlist", "policy", "grant"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenMcpProfiles),
        },
        PaletteEntry {
            id: "explorer.expand",
            title: "Expand or Open Table",
            keywords: &["tree", "open", "enter", "table"],
            shortcut: Some("Enter"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ExplorerExpand),
        },
        PaletteEntry {
            id: "explorer.refresh",
            title: "Refresh Catalog Node",
            keywords: &["reload", "tree"],
            shortcut: Some("r"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::RefreshCatalogNode),
        },
        PaletteEntry {
            id: "explorer.refresh_all",
            title: "Refresh Catalog",
            keywords: &["reload", "tree"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::RefreshCatalogAll),
        },
        PaletteEntry {
            id: "explorer.inspect",
            title: "Inspect Object",
            keywords: &["properties", "ddl"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenObjectInspector),
        },
        PaletteEntry {
            id: "explorer.ddl",
            title: "Open Object DDL",
            keywords: &["create", "script"],
            shortcut: Some("d"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenObjectDdl),
        },
        PaletteEntry {
            id: "explorer.refresh_subtree",
            title: "Refresh Catalog Subtree",
            keywords: &["reload", "tree"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::RefreshCatalogSubtree),
        },
        PaletteEntry {
            id: "explorer.up",
            title: "Explorer Up",
            keywords: &["tree", "select"],
            shortcut: Some("Up"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ExplorerUp),
        },
        PaletteEntry {
            id: "explorer.down",
            title: "Explorer Down",
            keywords: &["tree", "select"],
            shortcut: Some("Down"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ExplorerDown),
        },
        PaletteEntry {
            id: "explorer.dependencies",
            title: "Show Dependencies",
            keywords: &["depends", "inspector"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenDependencies),
        },
        PaletteEntry {
            id: "explorer.dependents",
            title: "Show Dependents",
            keywords: &["used", "inspector"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenDependents),
        },
        PaletteEntry {
            id: "tab.sql",
            title: "Tab SQL",
            keywords: &["workbench"],
            shortcut: Some("Ctrl+1"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SwitchTab { index: 0 }),
        },
        PaletteEntry {
            id: "tab.data",
            title: "Tab Data",
            keywords: &["workbench"],
            shortcut: Some("Ctrl+2"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SwitchTab { index: 1 }),
        },
        PaletteEntry {
            id: "tab.ddl",
            title: "Tab DDL",
            keywords: &["workbench"],
            shortcut: Some("Ctrl+3"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SwitchTab { index: 2 }),
        },
        PaletteEntry {
            id: "tab.properties",
            title: "Tab Properties",
            keywords: &["workbench"],
            shortcut: Some("Ctrl+4"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SwitchTab { index: 3 }),
        },
        PaletteEntry {
            id: "tab.explain",
            title: "Tab Explain",
            keywords: &["workbench"],
            shortcut: Some("Ctrl+5"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SwitchTab { index: 4 }),
        },
        PaletteEntry {
            id: "tab.next",
            title: "Next Tab",
            keywords: &["workbench"],
            shortcut: Some("Ctrl+Tab"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::NextTab),
        },
        PaletteEntry {
            id: "document.next",
            title: "Next Document",
            keywords: &["editor", "tab"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::NextDocument),
        },
        PaletteEntry {
            id: "document.new",
            title: "New Document",
            keywords: &["editor", "scratch"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::NewDocument),
        },
        PaletteEntry {
            id: "document.save",
            title: "Save Document",
            keywords: &["file", "write"],
            shortcut: Some("Ctrl+S"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SaveActiveDocument),
        },
        PaletteEntry {
            id: "document.open",
            title: "Open Document",
            keywords: &["file", "load"],
            shortcut: Some("Ctrl+O"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenDocument),
        },
        PaletteEntry {
            id: "results.select_row",
            title: "Select Grid Row",
            keywords: &["grid"],
            shortcut: Some("r"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SelectGridRow),
        },
        PaletteEntry {
            id: "results.select_column",
            title: "Select Grid Column",
            keywords: &["grid"],
            shortcut: Some("c"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SelectGridColumn),
        },
        PaletteEntry {
            id: "results.next_tab",
            title: "Next Result Tab",
            keywords: &["grid"],
            shortcut: Some("]"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::NextResultTab),
        },
        PaletteEntry {
            id: "results.prev_tab",
            title: "Previous Result Tab",
            keywords: &["grid"],
            shortcut: Some("["),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::PrevResultTab),
        },
        PaletteEntry {
            id: "inspector.next_tab",
            title: "Next Inspector Tab",
            keywords: &["ddl", "privileges"],
            shortcut: Some("Tab"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::InspectorNextTab),
        },
        PaletteEntry {
            id: "settings.theme",
            title: "Cycle Theme",
            keywords: &["dark", "light"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CycleTheme),
        },
        PaletteEntry {
            id: "settings.keymap",
            title: "Cycle Keymap",
            keywords: &["vim", "emacs"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CycleKeymap),
        },
        PaletteEntry {
            id: "settings.mouse",
            title: "Toggle Mouse",
            keywords: &["pointer"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ToggleMouse),
        },
        PaletteEntry {
            id: "explorer.data",
            title: "Open Object Data",
            keywords: &["rows", "table"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenObjectData),
        },
        PaletteEntry {
            id: "editor.goto",
            title: "Go To Definition",
            keywords: &["navigate", "catalog"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::GoToDefinition),
        },
        PaletteEntry {
            id: "explorer.copy_name",
            title: "Copy Object Name",
            keywords: &["clipboard", "tree"],
            shortcut: Some("c"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ExplorerCopyName),
        },
        PaletteEntry {
            id: "explorer.copy_simple",
            title: "Copy Simple Name",
            keywords: &["clipboard", "tree"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CopySimpleName),
        },
        PaletteEntry {
            id: "explorer.copy_ddl",
            title: "Copy DDL",
            keywords: &["clipboard", "create"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CopyDdl),
        },
        PaletteEntry {
            id: "explorer.favorite",
            title: "Toggle Favorite",
            keywords: &["star", "pin"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ToggleFavorite),
        },
        PaletteEntry {
            id: "explorer.favorites_only",
            title: "Show Favorites Only",
            keywords: &["filter", "star"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ToggleFavoritesOnly),
        },
        PaletteEntry {
            id: "explorer.system_objects",
            title: "Toggle System Objects",
            keywords: &["filter", "pg_catalog", "mysql"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ToggleSystemObjects),
        },
        PaletteEntry {
            id: "results.up",
            title: "Results Up",
            keywords: &["grid", "scroll"],
            shortcut: Some("Up"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsUp),
        },
        PaletteEntry {
            id: "results.down",
            title: "Results Down",
            keywords: &["grid", "scroll"],
            shortcut: Some("Down"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsDown),
        },
        PaletteEntry {
            id: "results.left",
            title: "Results Left",
            keywords: &["grid", "scroll", "columns"],
            shortcut: Some("Left"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsLeft),
        },
        PaletteEntry {
            id: "results.right",
            title: "Results Right",
            keywords: &["grid", "scroll", "columns"],
            shortcut: Some("Right"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsRight),
        },
        PaletteEntry {
            id: "results.pageup",
            title: "Results Page Up",
            keywords: &["grid", "scroll"],
            shortcut: Some("PageUp"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsPageUp),
        },
        PaletteEntry {
            id: "results.pagedown",
            title: "Results Page Down",
            keywords: &["grid", "scroll"],
            shortcut: Some("PageDown"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsPageDown),
        },
        PaletteEntry {
            id: "results.top",
            title: "Results Top",
            keywords: &["grid", "home"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsTop),
        },
        PaletteEntry {
            id: "results.extend_up",
            title: "Extend Results Selection Up",
            keywords: &["grid", "shift", "select"],
            shortcut: Some("Shift+Up"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsExtendUp),
        },
        PaletteEntry {
            id: "results.extend_down",
            title: "Extend Results Selection Down",
            keywords: &["grid", "shift", "select"],
            shortcut: Some("Shift+Down"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ResultsExtendDown),
        },
        PaletteEntry {
            id: "results.actions",
            title: "Results Row Actions",
            keywords: &["grid", "copy", "menu"],
            shortcut: Some("Enter"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenResultsMenu),
        },
        PaletteEntry {
            id: "results.toggle_pick",
            title: "Toggle Results Row Pick",
            keywords: &["grid", "ctrl", "select"],
            shortcut: Some("Ctrl+Enter"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ToggleResultsPick),
        },
        PaletteEntry {
            id: "connection.add",
            title: "Add Connection",
            keywords: &["database", "postgres", "mysql", "connect"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenConnectionForm),
        },
        PaletteEntry {
            id: "connection.browse",
            title: "Browse Connections",
            keywords: &["database", "sessions", "profiles"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenConnections),
        },
        PaletteEntry {
            id: "connection.connect",
            title: "Connect Selected",
            keywords: &["session"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ConnectSelected),
        },
        PaletteEntry {
            id: "connection.duplicate",
            title: "Duplicate Connection",
            keywords: &["copy", "profile"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::DuplicateConnection),
        },
        PaletteEntry {
            id: "connection.test",
            title: "Test Connection",
            keywords: &["ping"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::TestConnection),
        },
        PaletteEntry {
            id: "connection.delete",
            title: "Delete Connection",
            keywords: &["remove"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::DeleteConnection),
        },
        PaletteEntry {
            id: "connection.close_session",
            title: "Close Session",
            keywords: &["disconnect"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::CloseSelectedSession),
        },
        PaletteEntry {
            id: "project.browse",
            title: "Browse Projects",
            keywords: &["workspace", "switch"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenProjects),
        },
        PaletteEntry {
            id: "project.switch",
            title: "Switch Project",
            keywords: &["workspace", "open"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::OpenFlow(FlowIntent::ProjectSwitch),
        },
        PaletteEntry {
            id: "project.create",
            title: "Create Project",
            keywords: &["workspace", "new"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::OpenFlow(FlowIntent::ProjectCreate),
        },
        PaletteEntry {
            id: "project.rename",
            title: "Rename Project",
            keywords: &["workspace"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::OpenFlow(FlowIntent::ProjectRename),
        },
        PaletteEntry {
            id: "project.delete",
            title: "Delete Project",
            keywords: &["workspace"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::OpenFlow(FlowIntent::ProjectDelete),
        },
        PaletteEntry {
            id: "config.transfer",
            title: "Import/Export Config",
            keywords: &["portable", "toml"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenConfigTransfer),
        },
        PaletteEntry {
            id: "settings.open",
            title: "Open Settings",
            keywords: &["theme", "keymap", "mouse"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenSettings),
        },
        PaletteEntry {
            id: "settings.reset",
            title: "Reset Settings",
            keywords: &["defaults"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ConfirmResetSettings),
        },
        PaletteEntry {
            id: "recovery.open",
            title: "Session Recovery",
            keywords: &["crash", "restore"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenRecovery),
        },
        PaletteEntry {
            id: "recovery.restore",
            title: "Recover Session",
            keywords: &["crash"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ConfirmRecover),
        },
        PaletteEntry {
            id: "recovery.discard",
            title: "Discard Recovery",
            keywords: &["crash"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ConfirmDiscardRecovery),
        },
        PaletteEntry {
            id: "mcp.audit",
            title: "MCP Audit Log",
            keywords: &["mcp", "grant", "revoke"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenMcpAudit),
        },
        PaletteEntry {
            id: "mcp.revoke_all",
            title: "Revoke All MCP Grants",
            keywords: &["mcp", "grant"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::RevokeAllMcpGrants),
        },
        PaletteEntry {
            id: "editor.complete",
            title: "Trigger Completion",
            keywords: &["intellisense", "suggest"],
            shortcut: Some("Ctrl+Space"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::RefreshSqlIntelligence),
        },
        PaletteEntry {
            id: "editor.format",
            title: "Format SQL",
            keywords: &["pretty", "indent"],
            shortcut: Some("Ctrl+Shift+I"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::FormatSql),
        },
        PaletteEntry {
            id: "editor.accept_completion",
            title: "Accept Completion",
            keywords: &["complete"],
            shortcut: Some("Tab"),
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::AcceptCompletion),
        },
        PaletteEntry {
            id: "editor.snippet",
            title: "Insert Snippet",
            keywords: &["snippet", "template"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::InsertSnippet),
        },
        PaletteEntry {
            id: "editor.parameters",
            title: "Submit Parameters",
            keywords: &["bind", "params"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SubmitParameters),
        },
        PaletteEntry {
            id: "editor.history",
            title: "Search History",
            keywords: &["rerun", "sql"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::SearchHistory),
        },
        PaletteEntry {
            id: "editor.history.clear",
            title: "Clear History",
            keywords: &["history", "delete"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::ClearHistory),
        },
        PaletteEntry {
            id: "diagnostics.export",
            title: "Export Diagnostics",
            keywords: &["logs", "support"],
            shortcut: None,
            disabled_reason: None,
            requirements: &[],
            invocation: PaletteInvocation::Dispatch(Action::OpenDiagnostics),
        },
    ]
}
