[package]
name = "dexo-driver-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
dexo-driver-api = { path = "../dexo-driver-api" }
futures-util = "0.3"
rusqlite = { workspace = true, features = ["column_decltype"] }
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
secrecy.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
