[package]
name = "dexo-secrets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
keyring.workspace = true
secrecy.workspace = true
thiserror.workspace = true

[dev-dependencies]
secrecy.workspace = true
