-- ============================================================================
-- SISTEMA DE VENDAS - SCRIPT DE CRIACAO DO BANCO
-- Arquivo ...: 01_schema.sql
-- SGBD ......: PostgreSQL 12 ou superior
--
-- Premissas atendidas:
--   - venda_produto e a tabela associativa N:N entre venda e produto
--
-- Execucao: psql -U postgres -d vendas -f 01_schema.sql
-- ============================================================================
DROP TABLE IF EXISTS venda_produto CASCADE;

-- 4. ENDERECO  (tabela fraca em relacao a cliente: 1 cliente : N enderecos)
CREATE TABLE endereco (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    uf         CHAR(2) NOT NULL,
    CONSTRAINT ck_endereco_uf CHECK (uf = upper(uf) AND length(uf) = 2)
);

-- 8. VENDA_PRODUTO  (tabela associativa N:N entre VENDA e PRODUTO)
CREATE TABLE venda_produto (
    id              INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    quantidade      INTEGER       NOT NULL,
    preco_unitario  NUMERIC(10,2) NOT NULL,
    desconto_item   NUMERIC(10,2) NOT NULL DEFAULT 0,
    subtotal        NUMERIC(12,2) GENERATED ALWAYS AS
                        (quantidade * preco_unitario - desconto_item) STORED
);

COMMENT ON TABLE venda_produto IS 'Associativa N:N entre venda e produto (itens da venda)';
COMMENT ON COLUMN venda_produto.subtotal IS
    'Coluna gerada pelo banco: quantidade * preco_unitario - desconto_item';
