//! A table's DDL as `CREATE TABLE`: the columns with their types, defaults and
//! NOT NULL, the primary key, unique, check and foreign-key constraints, then the
//! indexes and comments. It used to be the column names and bare types only, so a
//! copied definition made a different table: no key, nullable, no default, no
//! foreign key, and `serial` turned into `integer`.

use dexo_driver_api::DriverError;

use crate::error::map_error;
use crate::session::PostgresSession;

/// One column as the catalog has it. Names are already quoted, the way the statement
/// writes them.
#[derive(Clone, Debug, Default, PartialEq)]
pub(super) struct ColumnParts {
    pub name: String,
    pub data_type: String,
    pub not_null: bool,
    /// `pg_get_expr` of the default, or of the expression of a generated column.
    pub default: Option<String>,
    /// `a` (ALWAYS) or `d` (BY DEFAULT) for an identity column.
    pub identity: Option<char>,
    /// `s` for a stored generated column.
    pub generated: Option<char>,
    /// The column owns the sequence its default draws on: `serial`.
    pub owns_sequence: bool,
    pub collation: Option<String>,
    pub comment: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq)]
pub(super) struct TableParts {
    /// `schema.table`, quoted.
    pub name: String,
    pub foreign: bool,
    pub unlogged: bool,
    /// `RANGE (placed_at)` and the like, on a partitioned table.
    pub partition_key: Option<String>,
    pub comment: Option<String>,
    pub columns: Vec<ColumnParts>,
    /// Name and definition, `pg_get_constraintdef`'s way: `PRIMARY KEY (id)`.
    pub constraints: Vec<(String, String)>,
    /// `CREATE INDEX ...`, without the closing semicolon.
    pub indexes: Vec<String>,
    /// A foreign table's server and options, as `SERVER s OPTIONS (...)`.
    pub server: Option<String>,
}

fn literal(text: &str) -> String {
    format!("'{}'", text.replace('\'', "''"))
}

fn column_line(column: &ColumnParts) -> String {
    let mut line = format!("  {} ", column.name);
    // A serial is an integer whose default draws on a sequence it owns; written out as
    // `integer DEFAULT nextval(...)` it would need the sequence made first.
    let serial = match (
        column.owns_sequence,
        column.identity,
        column.default.as_deref(),
    ) {
        (true, None, Some(default)) if default.starts_with("nextval(") => {
            match column.data_type.as_str() {
                "smallint" => Some("smallserial"),
                "integer" => Some("serial"),
                "bigint" => Some("bigserial"),
                _ => None,
            }
        }
        _ => None,
    };
    line.push_str(serial.unwrap_or(&column.data_type));
    if let Some(collation) = &column.collation {
        line.push_str(&format!(" COLLATE {collation}"));
    }
    match (column.identity, column.generated, &column.default) {
        (Some('a'), _, _) => line.push_str(" GENERATED ALWAYS AS IDENTITY"),
        (Some(_), _, _) => line.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
        (None, Some(_), Some(expression)) => {
            line.push_str(&format!(" GENERATED ALWAYS AS ({expression}) STORED"));
        }
        (None, None, Some(default)) if serial.is_none() => {
            line.push_str(&format!(" DEFAULT {default}"));
        }
        _ => {}
    }
    // A serial and an identity column are NOT NULL by what they are.
    if column.not_null && serial.is_none() && column.identity.is_none() {
        line.push_str(" NOT NULL");
    }
    line
}

pub(super) fn render(table: &TableParts) -> String {
    let mut lines: Vec<String> = table.columns.iter().map(column_line).collect();
    // A foreign table has no keys of its own to write.
    if !table.foreign {
        lines.extend(
            table
                .constraints
                .iter()
                .map(|(name, definition)| format!("  CONSTRAINT {name} {definition}")),
        );
    }
    let kind = if table.foreign {
        "FOREIGN TABLE"
    } else if table.unlogged {
        "UNLOGGED TABLE"
    } else {
        "TABLE"
    };
    let mut sql = format!("CREATE {kind} {} (\n{}\n)", table.name, lines.join(",\n"));
    if let Some(key) = &table.partition_key {
        sql.push_str(&format!(" PARTITION BY {key}"));
    }
    if let Some(server) = &table.server {
        sql.push_str(&format!("\n{server}"));
    }
    sql.push(';');
    for index in &table.indexes {
        sql.push_str(&format!("\n\n{index};"));
    }
    let kind = if table.foreign {
        "FOREIGN TABLE"
    } else {
        "TABLE"
    };
    if let Some(comment) = &table.comment {
        sql.push_str(&format!(
            "\n\nCOMMENT ON {kind} {} IS {};",
            table.name,
            literal(comment)
        ));
    }
    for column in &table.columns {
        if let Some(comment) = &column.comment {
            sql.push_str(&format!(
                "\nCOMMENT ON COLUMN {}.{} IS {};",
                table.name,
                column.name,
                literal(comment)
            ));
        }
    }
    sql
}

impl PostgresSession {
    /// The `CREATE TABLE` of the relation with this oid.
    pub(super) async fn table_ddl(&self, oid: i64) -> Result<String, DriverError> {
        let head = self
            .client
            .query_one(
                "SELECT quote_ident(n.nspname) || '.' || quote_ident(c.relname),
                        c.relkind::text, c.relpersistence::text,
                        CASE WHEN c.relkind = 'p' THEN pg_get_partkeydef(c.oid) END,
                        obj_description(c.oid, 'pg_class'),
                        (SELECT 'SERVER ' || quote_ident(s.srvname) ||
                                coalesce(E'\\nOPTIONS (' ||
                                    (SELECT string_agg(quote_ident(o.option_name) || ' ' || quote_literal(o.option_value), ', ')
                                     FROM pg_options_to_table(ft.ftoptions) o) || ')', '')
                         FROM pg_foreign_table ft
                         JOIN pg_foreign_server s ON s.oid = ft.ftserver
                         WHERE ft.ftrelid = c.oid)
                 FROM pg_class c
                 JOIN pg_namespace n ON n.oid = c.relnamespace
                 WHERE c.oid = $1::bigint::oid",
                &[&oid],
            )
            .await
            .map_err(map_error)?;
        let relkind: String = head.get(1);
        let persistence: String = head.get(2);
        let mut table = TableParts {
            name: head.get(0),
            foreign: relkind == "f",
            unlogged: persistence == "u",
            partition_key: head.get(3),
            comment: head.get(4),
            server: head.get(5),
            ..TableParts::default()
        };
        let columns = self
            .client
            .query(
                "SELECT quote_ident(a.attname), format_type(a.atttypid, a.atttypmod), a.attnotnull,
                        pg_get_expr(d.adbin, d.adrelid), a.attidentity::text, a.attgenerated::text,
                        pg_get_serial_sequence(quote_ident(n.nspname) || '.' || quote_ident(c.relname), a.attname) IS NOT NULL,
                        CASE WHEN a.attcollation <> 0 AND a.attcollation <> t.typcollation
                             THEN (SELECT quote_ident(cn.nspname) || '.' || quote_ident(co.collname)
                                   FROM pg_collation co JOIN pg_namespace cn ON cn.oid = co.collnamespace
                                   WHERE co.oid = a.attcollation) END,
                        col_description(a.attrelid, a.attnum)
                 FROM pg_attribute a
                 JOIN pg_class c ON c.oid = a.attrelid
                 JOIN pg_namespace n ON n.oid = c.relnamespace
                 JOIN pg_type t ON t.oid = a.atttypid
                 LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                 WHERE a.attrelid = $1::bigint::oid AND a.attnum > 0 AND NOT a.attisdropped
                 ORDER BY a.attnum",
                &[&oid],
            )
            .await
            .map_err(map_error)?;
        let flag = |text: String| text.chars().next().filter(|ch| *ch != ' ' && *ch != '\0');
        table.columns = columns
            .into_iter()
            .map(|row| ColumnParts {
                name: row.get(0),
                data_type: row.get(1),
                not_null: row.get(2),
                default: row.get(3),
                identity: flag(row.get::<_, String>(4)),
                generated: flag(row.get::<_, String>(5)),
                owns_sequence: row.get(6),
                collation: row.get(7),
                comment: row.get(8),
            })
            .collect();
        if table.foreign {
            return Ok(render(&table));
        }
        let constraints = self
            .client
            .query(
                "SELECT quote_ident(conname), pg_get_constraintdef(oid, true)
                 FROM pg_constraint
                 WHERE conrelid = $1::bigint::oid AND contype IN ('p', 'u', 'c', 'f', 'x')
                   AND conparentid = 0
                 ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 ELSE 3 END,
                          conname",
                &[&oid],
            )
            .await
            .map_err(map_error)?;
        table.constraints = constraints
            .into_iter()
            .map(|row| (row.get(0), row.get(1)))
            .collect();
        // The indexes a constraint made are its own words; these are the rest.
        let indexes = self
            .client
            .query(
                "SELECT pg_get_indexdef(i.indexrelid)
                 FROM pg_index i
                 WHERE i.indrelid = $1::bigint::oid
                   AND NOT EXISTS (SELECT 1 FROM pg_constraint k
                                   WHERE k.conindid = i.indexrelid AND k.conrelid = i.indrelid
                                     AND k.contype IN ('p', 'u', 'x'))
                 ORDER BY 1",
                &[&oid],
            )
            .await
            .map_err(map_error)?;
        table.indexes = indexes.into_iter().map(|row| row.get(0)).collect();
        Ok(render(&table))
    }
}

#[cfg(test)]
mod tests {
    use super::{ColumnParts, TableParts, render};

    fn column(name: &str, data_type: &str) -> ColumnParts {
        ColumnParts {
            name: name.into(),
            data_type: data_type.into(),
            ..ColumnParts::default()
        }
    }

    /// What the seed's `orders` is: a serial key, NOT NULL with a default, a foreign
    /// key, a check, an index and a comment.
    #[test]
    fn the_definition_has_what_makes_the_table_the_table() {
        let table = TableParts {
            name: "public.orders".into(),
            comment: Some("customers' orders".into()),
            columns: vec![
                ColumnParts {
                    owns_sequence: true,
                    default: Some("nextval('orders_id_seq'::regclass)".into()),
                    not_null: true,
                    ..column("id", "integer")
                },
                ColumnParts {
                    not_null: true,
                    comment: Some("who".into()),
                    ..column("customer_id", "integer")
                },
                ColumnParts {
                    not_null: true,
                    default: Some("'new'::order_status".into()),
                    ..column("status", "order_status")
                },
                column("note", "text"),
                ColumnParts {
                    identity: Some('a'),
                    not_null: true,
                    ..column("n", "bigint")
                },
            ],
            constraints: vec![
                ("orders_pkey".into(), "PRIMARY KEY (id)".into()),
                (
                    "orders_total_check".into(),
                    "CHECK (total >= 0::numeric)".into(),
                ),
                (
                    "orders_customer_id_fkey".into(),
                    "FOREIGN KEY (customer_id) REFERENCES customers(id)".into(),
                ),
            ],
            indexes: vec![
                "CREATE INDEX orders_status_idx ON public.orders USING btree (status)".into(),
            ],
            ..TableParts::default()
        };
        assert_eq!(
            render(&table),
            "CREATE TABLE public.orders (\n\
             \x20 id serial,\n\
             \x20 customer_id integer NOT NULL,\n\
             \x20 status order_status DEFAULT 'new'::order_status NOT NULL,\n\
             \x20 note text,\n\
             \x20 n bigint GENERATED ALWAYS AS IDENTITY,\n\
             \x20 CONSTRAINT orders_pkey PRIMARY KEY (id),\n\
             \x20 CONSTRAINT orders_total_check CHECK (total >= 0::numeric),\n\
             \x20 CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id)\n\
             );\n\
             \n\
             CREATE INDEX orders_status_idx ON public.orders USING btree (status);\n\
             \n\
             COMMENT ON TABLE public.orders IS 'customers'' orders';\n\
             COMMENT ON COLUMN public.orders.customer_id IS 'who';"
        );
    }

    #[test]
    fn a_foreign_table_keeps_its_server_and_options() {
        let table = TableParts {
            name: "public.remote_orders".into(),
            foreign: true,
            server: Some("SERVER elsewhere\nOPTIONS (table_name 'orders')".into()),
            columns: vec![column("id", "integer")],
            constraints: vec![("ignored".into(), "PRIMARY KEY (id)".into())],
            ..TableParts::default()
        };
        assert_eq!(
            render(&table),
            "CREATE FOREIGN TABLE public.remote_orders (\n  id integer\n)\nSERVER elsewhere\nOPTIONS (table_name 'orders');"
        );
    }

    #[test]
    fn a_partitioned_unlogged_table_and_a_stored_generated_column() {
        let table = TableParts {
            name: "public.events".into(),
            unlogged: true,
            partition_key: Some("RANGE (at)".into()),
            columns: vec![
                column("at", "timestamp with time zone"),
                ColumnParts {
                    generated: Some('s'),
                    default: Some("at::date".into()),
                    ..column("day", "date")
                },
            ],
            ..TableParts::default()
        };
        assert_eq!(
            render(&table),
            "CREATE UNLOGGED TABLE public.events (\n  at timestamp with time zone,\n  day date GENERATED ALWAYS AS (at::date) STORED\n) PARTITION BY RANGE (at);"
        );
    }
}
